version: '3'
services:
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500  #Needs to expose consult to be reachable from registrator

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul:consul
    command: -cleanup  -deregister="always" -internal=false  -resync=10 -ttl=6 -ttl-refresh=5  consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

