version: '3'
services:
  consul:
    image: consul
    container_name: consul
    ports:
    - 8500:8500  #Needs to expose consult to be reachable from registrator

  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul:consul
    command: -cleanup  -deregister="always" -internal=false  -resync=10 -ttl=6 -ttl-refresh=5  consul://consul:8500
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  loadbalancer:
    image: nginx-lb:v0.01-27-gee67901
    network_mode: "host"
    ports:
    - 80:80
